repos:
  - repo: local
    hooks:
      - id: check-conflict-markers
        name: Check for merge conflict markers
        entry: python tools/check_conflicts.py
        language: python
        files: ''
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
