[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "railweb"
version = "0.0.0"
description = "Railweb prototype utilities"
authors = [ { name = "railweb" } ]
