import json
import subprocess
from pathlib import Path


def test_detect_copilot_stdin(tmp_path):
    p = tmp_path / "sample.txt"
    p.write_text("This file was generated by GitHub Copilot.\nNormal line\nCo-authored-by: Someone <s@example.com>\n")

    proc = subprocess.run(["python", "tools/detect_copilot.py", "--json"], input=p.read_text(), text=True, capture_output=True)
    assert proc.returncode == 1
    out = json.loads(proc.stdout)
    assert out["matches"]


def test_detect_copilot_file(tmp_path):
    p = tmp_path / "sample2.txt"
    p.write_text("Just a normal file\nNothing special\n")

    proc = subprocess.run(["python", "tools/detect_copilot.py", str(p), "--json"], capture_output=True, text=True)
    assert proc.returncode == 0
    out = json.loads(proc.stdout)
    assert out["matches"] == []
