name: Block Copilot assignment without label

on:
  issues:
    types: [assigned]

jobs:
  enforce-copilot-label:
    name: Enforce copilot-eligible label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check Copilot assignment and labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const assignees = (issue.assignees || []).map(a => a.login);
            const hasCopilot = assignees.includes('github-copilot');
            if (!hasCopilot) {
              return 'No Copilot assignee; nothing to do.';
            }
            const labels = (issue.labels || []).map(l => l.name);
            if (labels.includes('copilot-eligible')) {
              return 'copilot-eligible label present; assignment allowed.';
            }
            // Remove the Copilot assignment and notify
            await github.rest.issues.removeAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: ['github-copilot'],
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: 'Automated policy: this issue was assigned to GitHub Copilot but is missing the `copilot-eligible` label. The assignment has been removed. Please add the `copilot-eligible` label before assigning Copilot.',
            });
            return 'Removed Copilot assignment and left a comment.';
