name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check . || true
      - name: Install test deps
        run: |
          pip install pytest jsonschema
      - name: Run tests
        run: |
          if [ -d tests ]; then pytest -q; else echo 'No tests dir'; fi
      - name: Run metadata validator
        run: |
          # validate any out_audio.metadata.json found under prototype
          for f in $(git ls-files 'prototype/**/out_audio.metadata.json'); do
            echo "Validating $f";
            python scripts/validate_metadata.py "$f" || exit 2;
          done || true
