name: Conflict marker check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps (none required)
        run: python -V
      - name: Run conflict marker scan
        run: |
          python tools/check_conflicts.py
