name: Debate tests

on:
  push:
    branches: [ main, feature/railweb-mvp ]
  pull_request:
    branches: [ main, feature/railweb-mvp ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Run tests
        run: |
          echo "## Setting PYTHONPATH to repository root"
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          python -m pytest -q
