name: Handoff validation

on:
  pull_request:
    paths:
      - 'handoff/**'
      - 'scripts/validate_handoff.py'
  push:
    paths:
      - 'handoff/**'
      - 'scripts/validate_handoff.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema
      - name: Validate JSON example
        run: |
          python scripts/validate_handoff.py handoff/requirements-to-planner-architect.example.json
